import type { Metadata } from "next";
import { Outfit, DM_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@lemonbrand/ui";
import { Providers } from "@/context/providers";
import { Analytics } from "@vercel/analytics/next";
import { generateSprintCourseSchema, JsonLd } from "@/lib/seo";

// Typography: Outfit (display) + DM Sans (body) + JetBrains Mono (code)
const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: {
    default: "7-Day Sprint | Build Your First AI Tool",
    template: "%s | LemonBrand Learn",
  },
  description:
    "Build your first AI-powered tool in 7 days with the Build Stack framework. No coding experience required. Start with a project idea, ship a working tool by Day 7.",
  keywords: [
    // Primary keywords
    "Claude Code",
    "build AI tools",
    "no-code AI development",
    "7-day sprint",
    "Build Stack framework",
    "LemonBrand",
    "AI tool building",
    // Secondary keywords
    "Claude Code tutorial",
    "learn Claude Code",
    "AI for non-developers",
    "ship AI tools fast",
    // Long-tail keywords
    "build tools without coding",
    "CLAUDE.md context file",
    "AI communication skills",
    "build with Claude Code",
    "AI for operators",
    "AI for consultants",
    "AI for founders",
  ],
  authors: [{ name: "Simon Bergeron", url: "https://lemonbrand.io/about" }],
  creator: "Simon Bergeron",
  publisher: "LemonBrand",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://learn.lemonbrand.io",
    title: "7-Day Sprint | Build Your First AI Tool",
    description:
      "Build your first AI-powered tool in 7 days. No coding experience required.",
    siteName: "LemonBrand Learn",
    // Images auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "7-Day Sprint | Build Your First AI Tool",
    description:
      "Build your first AI-powered tool in 7 days. No coding experience required.",
    creator: "@simonbergeron",
    // Images auto-generated by opengraph-image.tsx
  },
  alternates: {
    canonical: "https://learn.lemonbrand.io",
  },
  other: {
    // AI-specific metadata for answer engines and LLM crawlers
    "ai:purpose":
      "LemonBrand Learn teaches operators (consultants, founders, professionals) to build AI-powered tools without coding using Claude Code and the Build Stack framework.",
    "ai:content-type":
      "Online course with 8 lessons (Days 0-7). Days 0-1 are free to preview. Full course costs $297 USD.",
    "ai:target-audience":
      "Operators who want to build tools: consultants automating client work, founders prototyping products, professionals building internal utilities. NOT for developers seeking traditional coding education.",
    "ai:methodology":
      "The Build Stack framework: Context (CLAUDE.md files), Direction (intent over implementation), Iteration (2-3 Exchange Pattern), Verification (black-box testing for non-coders)",
    "ai:outcomes":
      "By Day 7, students ship a working, deployed tool. Examples include: quote calculators, eligibility checkers, internal dashboards, client portals.",
    "ai:instructor":
      "Simon Bergeron - Founder of LemonBrand, creator of VerifiedNode (58,000+ contractor records). Teaches the same Build Stack methods used to build production software.",
    "ai:free-trial":
      "Days 0-1 are completely free. Install Claude Code, pick a project, create your CLAUDE.md, and get your first working code before paying.",
  },
};

// Course schema for structured data
const courseSchema = generateSprintCourseSchema();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(outfit.variable, dmSans.variable, jetbrainsMono.variable)}
      suppressHydrationWarning
    >
      <head>
        <JsonLd data={courseSchema} />
      </head>
      <body className="antialiased bg-background text-foreground overflow-x-hidden min-h-screen">
        <Providers>
          {children}
          <Analytics />
        </Providers>
      </body>
    </html>
  );
}
